### ISSUE TITLE
Team Battle Agent does not have health

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/Abmarl#278]
```
python3 team_battle_example.py 
Traceback (most recent call last):
  File "team_battle_example.py", line 126, in <module>
    sim.reset()
  File "team_battle_example.py", line 46, in reset
    self.position_state.reset(**kwargs)
  File "/Users/rusu1/Abmarl/abmarl/sim/gridworld/state.py", line 41, in reset
    assert self.grid.place(agent, (r, c)), "All initial positions must " + \
  File "/Users/rusu1/Abmarl/abmarl/sim/gridworld/grid.py", line 104, in place
    if self.query(agent, ndx):
  File "/Users/rusu1/Abmarl/abmarl/sim/gridworld/grid.py", line 80, in query
    for other in self._internal[ndx].values() if other.active
  File "/Users/rusu1/Abmarl/abmarl/sim/gridworld/grid.py", line 80, in <listcomp>
    for other in self._internal[ndx].values() if other.active
  File "/Users/rusu1/Abmarl/abmarl/sim/gridworld/agent.py", line 202, in active
    return self.health > 0
  File "/Users/rusu1/Abmarl/abmarl/sim/gridworld/agent.py", line 176, in health
    return self._health
AttributeError: 'BattleAgent' object has no attribute '_health'
```

**Comment by rusu24edward** [comment]
This issue arises because we changed the internal grid so that it checks if the agents are active when checking for overlap. Health agents overwrite the active property, using their internal health. Their internal health is not set until the HealthState sets it, which in this case happens after the PositionState attempt to set the positions.

There is not way to enforce that health state will reset first. This is a bad design anyways.

The PrincipleAgent has an active property. We did not give it a setter because we didn't think it needed one. However, we have a setter for id and seed, which are properties that we don't expect to change. Active is a changing property, so we should give it a setter. But the HealthAgent still overwrites the active property based on health, so we will still have the issue that there is not internal health yet.

The activeness of an agent is something that is deeper than a component since it is used by the Grid and lives in the PrincipleAgent. We need to modify the framework design to deal with this better. For now, we'll just switch the order of the resets.
