### ISSUE TITLE
Visualize with record fails in Python 3.9

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/Abmarl#395]
When I visualize a policy with the `--record` flag on, I get an error. Without this flag, the visualization works, although it has some trouble closing the figure after the first episode completes. Here's the error code:
```
Episode: 0
/usr/WS1/rusu1/Abmarl/abmarl/stage.py:136: UserWarning: frames=<function run_visualize.<locals>.gen_frame_until_done at 0x15515b86f1f0> which we can infer the length of, did not pass an explicit *save_count* and passed cache_frame_data=True.  To avoid a possibly unbounded cache, frame data caching has been disabled. To suppress this warning either pass `cache_frame_data=False` or `save_count=MAX_FRAMES`.
  anim = FuncAnimation(
MovieWriter ffmpeg unavailable; using Pillow instead.
Traceback (most recent call last):
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/animation.py", line 233, in saving
    yield self
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/animation.py", line 1090, in save
    anim._init_draw()  # Clear the initial frame
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/animation.py", line 1748, in _init_draw
    self._draw_frame(frame_data)
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/animation.py", line 1767, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/usr/WS1/rusu1/Abmarl/abmarl/stage.py", line 124, in animate
    sim.render(fig=fig)
  File "/usr/WS1/rusu1/Abmarl/abmarl/external/gym_env_wrapper.py", line 60, in render
    self.sim.render(**kwargs)
  File "/usr/WS1/rusu1/Abmarl/abmarl/managers/simulation_manager.py", line 56, in render
    self.sim.render(**kwargs)
  File "/usr/WS1/rusu1/Abmarl/abmarl/sim/gridworld/base.py", line 216, in render
    plt.pause(1e-6)
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/pyplot.py", line 581, in pause
    show(block=False)
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/pyplot.py", line 446, in show
    return _get_backend_mod().show(*args, **kwargs)
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 3607, in show
    manager.show()  # Emits a warning for non-interactive backend.
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/backends/_backend_tk.py", line 559, in show
    self.canvas.manager.window.attributes('-topmost', 1)
AttributeError: 'NoneType' object has no attribute 'window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/bin/abmarl", line 33, in <module>
    sys.exit(load_entry_point('abmarl', 'console_scripts', 'abmarl')())
  File "/usr/WS1/rusu1/Abmarl/abmarl/scripts/scripts.py", line 59, in cli
    visualize.run(path_config, parameters)
  File "/usr/WS1/rusu1/Abmarl/abmarl/scripts/visualize_script.py", line 35, in run
    stage.run_visualize(full_trained_directory, parameters)
  File "/usr/WS1/rusu1/Abmarl/abmarl/stage.py", line 141, in run_visualize
    anim.save(os.path.join(full_trained_directory, 'Episode_{}.mp4'.format(episode)))
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/animation.py", line 1107, in save
    writer.grab_frame(**savefig_kwargs)
  File "/collab/usr/gapps/python/build/spack-toss4.1/var/spack/environments/python/._view/75prb56irmif5ejtirjthpx6kq3gqo52/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/animation.py", line 235, in saving
    self.finish()
  File "/usr/WS1/rusu1/virtual_envs/v_deterrence_39/lib/python3.9/site-packages/matplotlib/animation.py", line 501, in finish
    self._frames[0].save(
IndexError: list index out of range
```

**Comment by rusu24edward** [comment]
I only see this error on LC, not on my local mac. May be a backend issue.

**Comment by rusu24edward** [comment]
Can work around this by using the Agg backend and using record. This will only generate the videos and will not display them on the screen. Still need to fix the issue, but this would be a nice feature to add.

**Comment by rusu24edward** [comment]
Animation tries to use ffmpeg, but it is not installed, so it switches to Pillow.

**Comment by rusu24edward** [comment]
Maybe I need an `init_func` for the Animator?

**Comment by rusu24edward** [comment]
The canvas manager is None, so it has no window

**Comment by rusu24edward** [comment]
On the mac, if I switch to the PillowWriter, then I can duplicate the error.

**Comment by rusu24edward** [comment]
Consider the following [backends](https://matplotlib.org/stable/users/explain/backends.html#the-builtin-backends):
- [ ] QtAgg - Requires PyQt or PySide
- [ ] GTK3Agg - Requires PyGObject and pycairo
- [ ] GTK4Agg - Requires PyGObject and pycairo
- [ ] TkAgg - Requires TkInter
- [ ] WebAgg - starts tornado server
- [ ] GTK3Cairo - Requires PyGObject and pycairo
- [ ] GTK4Cairo - Requires PyGObject and pycairo
- [ ] wxAgg - Requires wxPython4
