### ISSUE TITLE
Visualize --record-only expects local_dir in config

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/Abmarl#482]
Episode: 0
Traceback (most recent call last):
  File "/g/g13/rusu1/v_abmarl_39/bin/abmarl", line 33, in <module>
    sys.exit(load_entry_point('abmarl', 'console_scripts', 'abmarl')())
  File "/g/g13/rusu1/abmarl/abmarl/scripts/scripts.py", line 65, in cli
    visualize.run(path_config, parameters)
  File "/g/g13/rusu1/abmarl/abmarl/scripts/visualize_script.py", line 43, in run
    visualize(params, full_trained_directory, **vars(parameters))
  File "/g/g13/rusu1/abmarl/abmarl/stage.py", line 166, in visualize
    os.path.join(params['ray_tune']['local_dir'], 'Episode_{}.gif'.format(episode))
KeyError: 'local_dir'

**Comment by rusu24edward** [comment]
We changed this in #236, where we save animations using `local_dir` instead of `full_trained_directory`. Not clear why that change mattered, so probably want to go back to using that.
